<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShaderLibrary\ShaderLibrary.csproj" />
    <ProjectReference Include="..\..\BntxSharp\src\BntxSharp\BntxSharp.csproj" />
    <ProjectReference Include="..\..\McSharp\src\McSharp\McSharp.csproj" />
    <ProjectReference Include="..\..\TxtgSharp\src\TxtgSharp\TxtgSharp.csproj" />
    <ProjectReference Include="..\..\Yaz0Sharp\src\Yaz0Sharp\Yaz0Sharp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BfresLibrary">
      <HintPath>Libs\Bfres\BfresLibrary.dll</HintPath>
    </Reference>
    <Reference Include="Ryujinx.Common">
      <HintPath>Libs\Ryujinx.Common.dll</HintPath>
    </Reference>
    <Reference Include="Ryujinx.Graphics.Shader">
      <HintPath>Libs\Ryujinx.Graphics.Shader.dll</HintPath>
    </Reference>
    <Reference Include="Spv.Generator">
      <HintPath>Libs\Spv.Generator.dll</HintPath>
    </Reference>
    <Reference Include="Syroot.BinaryData">
      <HintPath>Libs\Bfres\Syroot.BinaryData.dll</HintPath>
    </Reference>
    <Reference Include="Syroot.Maths">
      <HintPath>Libs\Bfres\Syroot.Maths.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="libszs.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Libs\Ryujinx License.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Libs\UAM License.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="README.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Shaders\SMO\Pixel.frag">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Shaders\SMO\Vertex.vert">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="uam.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SarcLibrary" Version="3.3.5" />
  </ItemGroup>

</Project>
